title: digits
description: Digits is a web app for managing contacts and logging timestamped interaction notes.
google_analytics:
show_downloads: true
theme: jekyll-theme-lanyon

gems:
  - jekyll-mentions
